spring:
  application:
    name: task-api
  datasource:
    url: jdbc:postgresql://localhost:5432/task?reWriteBatchedInserts=true
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog.xml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /api
